watch_stylesheet: true
watch_config: true
debug: false
komorebi:
  start_command: "komorebic start --whkd"
  stop_command: "komorebic stop --whkd"
  reload_command: "komorebic reload-configuration"
bars:
  status-bar:
    enabled: true
    screens: ['*']
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    blur_effect:
      enabled: true
      acrylic: true
      dark_mode: true
      round_corners: true
      border_color: None
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 36
    padding:
      top: 8
      left: 8
      bottom: 8
      right: 8
    animation:
      enabled: false
      duration: 500
    widgets:
      left:
        [
          "wallpapers",
          "windows_workspaces",
          "active_window",
        ]
      center: [
          "clock",
          "weather"
        ]
      right:
        [
          "media",
          "apps",
          "komorebi_active_layout",
          "power_menu"
        ]
  wallpapers:
    type: "yasb.wallpapers.WallpapersWidget"
    options:
      label: "<span>\uf4e5</span>"
      image_path: "C:\\Users\\Lyric\\Pictures\\Wallpapers\\current"
      change_automatically: false
      update_interval: 600
      gallery:
          enabled: true
          blur: true
          image_width: 220
          image_per_page: 3
          show_buttons: false
          orientation: "landscape"
          image_spacing: 16
          lazy_load: false
          lazy_load_delay: 80
          lazy_load_fadein: 400
          image_corner_radius: 20
          enable_cache: true
  windows_workspaces:
    type: "yasb.windows_desktops.WorkspaceWidget"
    options:
      label_workspace_btn: "\udb81\udc3d"
      label_workspace_active_btn: "\udb81\udc3e"
      container_padding:
        top: 0
        left: 8
        bottom: 0
        right: 8
  active_window:
    type: "yasb.active_window.ActiveWindowWidget"
    options:
      label: "{win[title]}"
      label_alt: "[class='{win[class_name]}' exe='{win[process][name]}' hwnd={win[hwnd]}]"
      label_no_window: ""
      label_icon: true
      label_icon_size: 14
      max_length: 50
      max_length_ellipsis: "..."
      monitor_exclusive: true
  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "{%a %d, %b %H:%M}"
      label_alt: "{%A %d %B %Y, %H:%M}"
      locale: 'en_EN'
      timezones: ["America/Chicago"]
  weather:
    type: "yasb.weather.WeatherWidget"
    options:
      units: 'imperial'
      label: "<span>{icon}</span> {temp}"
      label_alt: "{location}: Min {min_temp}, Max {max_temp}, Humidity {humidity}"
      api_key: '3bf4cf9a7c3f40d6b31174128242807'
      update_interval: 600
      hide_decimal: true
      location: 'USA Okalahoma City 73128'
      callbacks:
        on_left: "toggle_label"
      icons:
        sunnyDay: "\ue30d"
        clearNight: "\ue32b"
        cloudyDay: "\udb81\udd99"
        cloudyNight: "\ue311"
        rainyDay: "\udb81\ude7e"
        rainyNight: "\udb81\ude7e"
        snowyIcyDay: "\udb81\udd98"
        snowyIcyNight: "\udb81\udd98"
        blizzard: "\uebaa"
        default: "\uebaa"
  media:
    type: "yasb.media.MediaWidget"
    options:
      label: "{title} - {artist}"
      label_alt: "{title}"
      max_field_size:
        label: 30
        label_alt: 30
      show_thumbnail: true
      controls_only: false
      controls_left: false
      hide_empty: false
      thumbnail_alpha: 50
      thumbnail_padding: 20
      thumbnail_corner_radius: 16
      icons:
        prev_track: "\ue892"
        next_track: "\ue893"
        play: "\ue768"
        pause: "\ue769"
  apps:
    type: "yasb.applications.ApplicationsWidget"
    options:
      label: "{data}"
      app_list:
        - {icon: "\uf422", launch: "search"}
        - {icon: "\ueb03", launch: "cmd /c Taskmgr"}
        - {icon: "\uf0a2", launch: "notification_center"}
        - {icon: "\ueb51", launch: "quick_settings"}
      container_padding:
        top: 0
        left: 5
        bottom: 0
        right: 5
  komorebi_active_layout:
    type: "komorebi.active_layout.ActiveLayoutWidget"
    options:
      hide_if_offline: true
      label: "{icon}"
      layouts: ['bsp', 'right_main_vertical_stack', 'ultrawide_vertical_stack']
      layout_icons:
        bsp: "BSP"
        right_main_vertical_stack: "RM-STACK"
        ultrawide_vertical_stack: "W-STACK"
        monocle: "MONOCLE"
        maximised: "MAX"
        floating: "FLOATING"
        paused: "PAUSED"
      callbacks:
        on_left: 'next_layout'
        on_middle: 'toggle_monocle'
        on_right: 'prev_layout'
  power_menu:
    type: "yasb.power_menu.PowerMenuWidget"
    options:
      label: "\u23fb"
      uptime: True
      blur: False
      blur_background: True
      animation_duration: 300 # Milisecond
      button_row: 3 # min 1 max 5
      buttons:
        lock: ["\uea75","Lock"]
        signout: ["\uf426","Sign out"]
        shutdown: ["\u23fb","Shut Down"]
        restart: ["\uead2","Restart"]
        hibernate: ["\uf28e","Hibernate"]
        cancel: ["\udb81\udf3a","Cancel"]
